class Format_Item_List(SequenceBase):  # pylint: disable=invalid-name
    """This class replaces the one generated by fparser. This class is
    required as support for hollerith strings makes matching more
    complicated.

    """

    use_names = []
    subclass_names = ["Format_Item"]

    @staticmethod
    def match(string):
        """Implements the matching for a list of format items.

        Supporting Hollerith strings makes it very difficult to
        correctly split the input string into items a-priori. The
        reason for this can be seen in the following example:

        `2H,x,e2.2` is `2H,x` and `e2.2` but when split with commas
        incorrectly gives `2H`, `x` and `e2.2`.

        Further, hollerith strings could also confuse any code that
        tried to determine whether code was inside quotes or not. For
        example::

            `2H"x,2H"x` does not mean that `x,2H` is part of a string.

        The solution chosen is to match one item at a time, first
        checking for a valid Hollerith string and then checking for
        any other valid input.

        :param str string: the string to match as a Format List.
        :return: None if there is no match or a tuple of size 2 \
        containing a string with a comma followed by a tuple \
        containing a list which itself contains the matched \
        format items.
        :rtype: (`str`, \
        ([:py:class:`fparser.two.Fortran2003.Format_Item`s])) or `NoneType`

        """
        if not string:
            return None
        current_string = string.lstrip()
        if not current_string:
            return None
        item_list = []
        while current_string:
            # Look for a slash edit descriptor with repeat modifier
            found, index = skip_digits(current_string)
            if found and current_string[index] == "/":
                item_list.append(Control_Edit_Desc(current_string[: index + 1]))
                current_string = current_string[index + 1 :].lstrip()
                # Rule C1002 allows omitting a comma after slash edit descriptors,
                # so skip the comma if it exists and carry on
                if current_string and current_string[0] == ",":
                    current_string = current_string[1:].lstrip()
                continue

            # Look for a colon edit descriptor or a slash edit descriptor without
            # a repeat modifier
            if current_string[0] in ":/":
                item_list.append(Control_Edit_Desc(current_string[0]))
                current_string = current_string[index + 1 :].lstrip()
                # Rule C1002 allows omitting a comma after colon or slash edit
                # descriptors, so skip the comma if it exists and carry on
                if current_string and current_string[0] == ",":
                    current_string = current_string[1:].lstrip()
                continue

            # Does the current item match the start of a
            # hollerith string?
            my_pattern = Hollerith_Item.match_pattern
            match = re.search(my_pattern, current_string)
            if match:
                # The current item matches with a hollerith string.
                match_str = match.group(0)
                hol_length_str = match_str[:-1]
                hol_length = int(hol_length_str)
                num_chars = len(match_str) + hol_length
                if len(current_string) < num_chars:
                    # The string is not long enough.
                    return None
                item_list.append(Hollerith_Item(current_string[:num_chars]))
                current_string = current_string[num_chars:].lstrip()
                if current_string:
                    if current_string[0] == ",":
                        # Remove the next comma and any white space.
                        current_string = current_string[1:].lstrip()
                    elif current_string[0] == "/":
                        # Commas aren't required before a slash edit descriptor without
                        # repeat modifier (C1002)
                        pass
                    elif current_string[0] == ":":
                        # Commas aren't required before a colon edit descriptor (C1002)
                        pass
                    else:
                        return None
            else:
                # Current item does not match with a hollerith string
                # so get the next format item by splitting on ',', '/' or ':'
                # after applying string_replace_map.
                line, repmap = string_replace_map(current_string)
                match = re.search("[,/:]", line)
                if match:
                    item_list.append(Format_Item(repmap(line[: match.start()])))
                    current_string = repmap(line[match.start() :])
                    if match.group() == ",":
                        # skip the comma
                        current_string = current_string[1:].lstrip()
                else:
                    item_list.append(Format_Item(repmap(line)))
                    current_string = ""
        return ",", tuple(item_list)
