from data_edit_desc import Data_Edit_Desc
from data_edit_desc_c1002 import Data_Edit_Desc_C1002
from r import R

class Format_Item(Base):  # pylint: disable=invalid-name
    """
    Fortran 2003 rule R1003::

        format-item is [ r ] data-edit-desc
                    or control-edit-desc
                    or char-string-edit-desc
                    or [ r ] ( format-item-list )
                    or format-item-c1002
                    or hollerith-item

    """

    subclass_names = [
        "Hollerith_Item",
        "Control_Edit_Desc",
        "Char_String_Edit_Desc",
        "Format_Item_C1002",
    ]
    use_names = ["R", "Format_Item_List", "Data_Edit_Desc"]

    @staticmethod
    def match(string):
        """Implements the matching of a Format Item. This method matches '[ r
        ] data-edit-desc' and '[ r ] ( format-item-list )'. The
        remaining options are matched via subclasses specified in the
        subclass_names variable.

        :param str string: A string or the Fortran reader containing the \
                    line of code that we are trying to match.
        :return: `None` if there is no match or a `tuple` of size 2 \
        containing an instance of the R class followed by an \
        instance of either the Format_Item_List or the Data_Edit_Desc \
        class.
        :rtype: `None` or ( :py:class:`fparser.two.Fortran2003.R`, \
        :py:class:`fparser.two.Fortran2003.Format_Item_List` or \
        :py:class:`fparser.two.Fortran2003.Data_Edit_Desc`)

        """
        if not string:
            return None
        strip_string = string.strip()
        if not strip_string:
            return None
        index = 0
        # Look for an optional repeat specifier (the 'r' in this rule)
        found, index = skip_digits(strip_string)
        rpart = None
        my_string = strip_string
        if found:
            # We found a repeat specifier (with content after it) so
            # create an R class using the value
            rpart = R(strip_string[:index])
            my_string = strip_string[index:].lstrip()
        # We deal with format-item-list and data-edit-desc in this
        # match method. Other matches are performed by the subclasses.
        if my_string[0] == "(" and my_string[-1] == ")":
            # This could be a format-item-list
            rest = Format_Item_List(my_string[1:-1].lstrip())
        else:
            # This is not a format-item-list so see if it is a
            # data-edit-descriptor
            rest = Data_Edit_Desc(my_string)
        return rpart, rest

    def tostr(self):
        """
        :return: Parsed representation of a Format Item.
        :rtype: str

        :raises InternalError: if the length of the internal items \
        list is not 2.
        :raises InternalError: if the first entry of the internal \
        items list has no content.

        """
        if len(self.items) != 2:
            raise InternalError(
                "Class Format_Item method tostr(): internal items list "
                "should be of length 2 but found '{0}'".format(len(self.items))
            )
        if not self.items[1]:
            raise InternalError(
                "Class Format_Item method tostr(): items list second entry "
                "should be a valid descriptor but it is empty or None"
            )
        rpart = self.items[0]
        rest = self.items[1]

        rpart_str = rpart if rpart else ""
        if isinstance(rest, (Data_Edit_Desc, Data_Edit_Desc_C1002)):
            return "{0}{1}".format(rpart_str, rest)
        return "{0}({1})".format(rpart_str, rest)


class Format_Item_List(SequenceBase):  # pylint: disable=invalid-name
    """This class replaces the one generated by fparser. This class is
    required as support for hollerith strings makes matching more
    complicated.

    """

    use_names = []
    subclass_names = ["Format_Item"]

    @staticmethod
    def match(string):
        """Implements the matching for a list of format items.

        Supporting Hollerith strings makes it very difficult to
        correctly split the input string into items a-priori. The
        reason for this can be seen in the following example:

        `2H,x,e2.2` is `2H,x` and `e2.2` but when split with commas
        incorrectly gives `2H`, `x` and `e2.2`.

        Further, hollerith strings could also confuse any code that
        tried to determine whether code was inside quotes or not. For
        example::

            `2H"x,2H"x` does not mean that `x,2H` is part of a string.

        The solution chosen is to match one item at a time, first
        checking for a valid Hollerith string and then checking for
        any other valid input.

        :param str string: the string to match as a Format List.
        :return: None if there is no match or a tuple of size 2 \
        containing a string with a comma followed by a tuple \
        containing a list which itself contains the matched \
        format items.
        :rtype: (`str`, \
        ([:py:class:`fparser.two.Fortran2003.Format_Item`s])) or `NoneType`

        """
        if not string:
            return None
        current_string = string.lstrip()
        if not current_string:
            return None
        item_list = []
        while current_string:
            # Look for a slash edit descriptor with repeat modifier
            found, index = skip_digits(current_string)
            if found and current_string[index] == "/":
                item_list.append(Control_Edit_Desc(current_string[: index + 1]))
                current_string = current_string[index + 1 :].lstrip()
                # Rule C1002 allows omitting a comma after slash edit descriptors,
                # so skip the comma if it exists and carry on
                if current_string and current_string[0] == ",":
                    current_string = current_string[1:].lstrip()
                continue

            # Look for a colon edit descriptor or a slash edit descriptor without
            # a repeat modifier
            if current_string[0] in ":/":
                item_list.append(Control_Edit_Desc(current_string[0]))
                current_string = current_string[index + 1 :].lstrip()
                # Rule C1002 allows omitting a comma after colon or slash edit
                # descriptors, so skip the comma if it exists and carry on
                if current_string and current_string[0] == ",":
                    current_string = current_string[1:].lstrip()
                continue

            # Does the current item match the start of a
            # hollerith string?
            my_pattern = Hollerith_Item.match_pattern
            match = re.search(my_pattern, current_string)
            if match:
                # The current item matches with a hollerith string.
                match_str = match.group(0)
                hol_length_str = match_str[:-1]
                hol_length = int(hol_length_str)
                num_chars = len(match_str) + hol_length
                if len(current_string) < num_chars:
                    # The string is not long enough.
                    return None
                item_list.append(Hollerith_Item(current_string[:num_chars]))
                current_string = current_string[num_chars:].lstrip()
                if current_string:
                    if current_string[0] == ",":
                        # Remove the next comma and any white space.
                        current_string = current_string[1:].lstrip()
                    elif current_string[0] == "/":
                        # Commas aren't required before a slash edit descriptor without
                        # repeat modifier (C1002)
                        pass
                    elif current_string[0] == ":":
                        # Commas aren't required before a colon edit descriptor (C1002)
                        pass
                    else:
                        return None
            else:
                # Current item does not match with a hollerith string
                # so get the next format item by splitting on ',', '/' or ':'
                # after applying string_replace_map.
                line, repmap = string_replace_map(current_string)
                match = re.search("[,/:]", line)
                if match:
                    item_list.append(Format_Item(repmap(line[: match.start()])))
                    current_string = repmap(line[match.start() :])
                    if match.group() == ",":
                        # skip the comma
                        current_string = current_string[1:].lstrip()
                else:
                    item_list.append(Format_Item(repmap(line)))
                    current_string = ""
        return ",", tuple(item_list)
